"""initial

Revision ID: 12fe9bb77c13
Revises: be3f72f81f03
Create Date: 2024-01-12 16:08:03.456874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fe9bb77c13'
down_revision = 'be3f72f81f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
